### ISSUE TITLE
Automated testing of visuals

### ISSUE THREAD

**Issue by fire** [godotengine/godot-tests#20] opened 2021-01-18 20:26 UTC
### Describe the project you are working on
Godot Engine

### Describe the problem or limitation you are having in your project
We do not have visual tests of Godot.

* GUI
* Rendering

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

Use robotframework to provide visual tests.

Need to evaluate:
* With Sikulix https://github.com/rainmanwy/robotframework-SikuliLibrary#readme
* With ScreenCapLibrary https://github.com/mihaiparvu/ScreenCapLibrary

https://robotframework.org/#documentation

### Describe how your proposal will work, with code, pseudo-code, mock-ups, and/or diagrams
We can use robotframework and pick one of the available frameworks that support vulkan.

### If this enhancement will not be used often, can it be worked around with a few lines of script?
Not a few lines of code. Should be ran every time.

### Is there a reason why this should be core and not an add-on in the asset library?
Also needs to integrate with cicd.

**Comment by Calinou** [comment] 2021-01-18 21:05
Duplicate of https://github.com/godotengine/godot-proposals/issues/1760. Feel free to comment there to bring additional information.

**Closed as completed by Calinou** 2021-01-18 21:05 UTC
Labels: enhancement
